### ISSUE TITLE
Confused about IPA while doing Chinese G2P.

### ISSUE THREAD

**Issue by andylida** [lingjzhu/CharsiuG2P#9]
Thanks for this great work!
Here is my problem：
```
data = 'zho-s: 你'
out = tokenizer(words,padding=True,add_special_tokens=False,return_tensors='pt')
preds = model.generate(**out,num_beams=1) 
phones = tokenizer.batch_decode(preds.tolist(),skip_special_tokens=True)
print(phones)
```
I searched from wiki, and what I expect is `ni˨˩˦`, however, the output is `ni˨˩˦ni˨˩˦`. In fact, for all mandarin, it doubles the output.
Is there some knowledge that I don't know about IPA which could explain this duplication?

Thanks!

**Comment by lingjzhu** [comment]
Oh sorry to hear that.
Currently, I do not have a good way to solve it given the black-box nature of the T5 model. Which model checkpoint did you use? Could you switch to other checkpoints? 

That's probably because the G2P model hadn't learned Mandarin well.  In our paper, the WER for Chinese is about 50% because the Chinese writing system is not transparent about its pronunciations. So a neural G2P is not suitable for Mandarin Chinese.  Such G2P models are more suitable for alphabetic writing systems. And repetition is a pretty common problem for text generation models.
You can definitely get more accurate pronunciations by querying the word in the [Mandarin pronunciation dictionary](https://github.com/lingjzhu/CharsiuG2P/blob/main/dicts/zho-s.tsv).

**Comment by lingjzhu** [comment]
Given that it doubles the output for all Mandarin words, it might be a problem in my preprocessing. I will check that again.

**Comment by enhuiz** [comment]
`'<zho-s>: 你'` gives a single `'ni˨˩˦'`. I guess you have to put a bracket around the language code.

**Comment by lingjzhu** [comment]
> `'<zho-s>: 你'` gives a single `'ni˨˩˦'`. I guess you have to put a bracket around the language code.

Thank you for your correction! You are absolutely right. Can't believe that I miss this typo.....

**Comment by enhuiz** [comment]
You are welcome!

**Comment by JohnHerry** [comment]
> Thanks for this great work! Here is my problem：
> 
> ```
> data = 'zho-s: 你'
> out = tokenizer(words,padding=True,add_special_tokens=False,return_tensors='pt')
> preds = model.generate(**out,num_beams=1) 
> phones = tokenizer.batch_decode(preds.tolist(),skip_special_tokens=True)
> print(phones)
> ```
> 
> I searched from wiki, and what I expect is `ni˨˩˦`, however, the output is `ni˨˩˦ni˨˩˦`. In fact, for all mandarin, it doubles the output. Is there some knowledge that I don't know about IPA which could explain this duplication?
> 
> Thanks!

Is that IPA phoneme? I can't read it, since the project had inferenced the g2pM polyphone data, I had guessed that it output as pinyin. How to convert pinyin into it?
